### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by belyaev-dev** [belyaev-dev/getcourse-js-sdk#7]
Needs investigation

```
{"level":50,"time":1691666294236,"pid":1,"hostname":"getcourse-amocrm-widget-7bb857bc9c-hb5sc","context":"AppProcessor","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'error_message')","stack":"TypeError: Cannot read properties of undefined (reading 'error_message')\n    at AppProcessor.createDeal (/dist/app.processor.js:516:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Worker.processJob (/node_modules/bullmq/dist/cjs/classes/worker.js:341:28)\n    at async Worker.retryIfFailed (/node_modules/bullmq/dist/cjs/classes/worker.js:524:24)"},"msg":"UnknownError"}
```

**Comment by belyaev-dev** [comment]
Некорректно отрабатывается ошибка
```{"success":false,"error":"Действие запрещено"}``` - ответ библиотеки

В Import API при success: false теперь отправляется error

Нужно обновить тип ImportApiResponse

```
export type ImportApiResponse<T> = {
  success: boolean
  action: string
  **error?: string**
  result: T
}
```
